### ISSUE TITLE
Adding new book on update

### ISSUE THREAD

**Issue by kurosh-wss** [justdjango/django_htmx_dynamic_forms#2]
When I try to update a book it will update it and render only the updated book (plus other books), but after reloading the page there is the book before the update and a new one (the updated one)

**Comment by mattfreire** [comment]
I have pushed a fix for this issue. You can view the fix [here](https://github.com/justdjango/django_htmx_dynamic_forms/commit/13f2bf04453d5230e42455f68213f2526ee1f6c9#diff-f0649f9b9fc3305e3488f0d423a3594b99b4cd250f5df7a612a8a5c1e66b715d)
